=== TimPaterson/ScreenDesigner-for-touchscreens/ScreenDesigner.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- definition of attributes -->
  <xs:attribute name="Name" type="xs:string"/>
  <xs:attribute name="RefName" type="xs:string"/>
  <xs:attribute name="Fill" type="xs:string"/>
  <xs:attribute name="Location" type="xs:string"/>
  <xs:attribute name="Height" type="xs:string"/>
  <xs:attribute name="Width" type="xs:string"/>
  <xs:attribute name="RowHeight" type="xs:string"/>
  <xs:attribute name="ColumnWidth" type="xs:string"/>
  <xs:attribute name="StrokeThickness" type="xs:string"/>
  <xs:attribute name="Stroke" type="xs:string"/>
  <xs:attribute name="Top" type="xs:string"/>
  <xs:attribute name="Left" type="xs:string"/>
  <xs:attribute name="Group" type="xs:string"/>
  <xs:attribute name="Value" type="xs:string"/>

  <xs:attributeGroup name="Element">
    <xs:attribute ref="Name"/>
    <xs:attribute ref="Top" />
    <xs:attribute ref="Left" />
    <xs:attribute ref="Location" />
    <xs:attribute ref="Group" />
    <xs:attribute ref="Value" />
  </xs:attributeGroup>

  <!-- definition of complex elements -->
  <xs:complexType name="TopContent_t">
    <xs:choice maxOccurs="unbounded">
      <xs:element ref="Grid" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="Rectangle" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="Ellipse" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="Line" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="TextBlock" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="Image" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="Set" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="Ref" minOccurs="0" maxOccurs="unbounded" />
      <xs:element ref="HotSpot" minOccurs="0" maxOccurs="unbounded" />
    </xs:choice>
  </xs:complexType>

  <xs:element name="Project">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="Component" maxOccurs="unbounded" />
        <xs:element ref="Canvas" maxOccurs="unbounded" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Component_t">
    <xs:complexContent>
      <xs:extension base="TopContent_t">
        <xs:attribute ref="Name" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="Component" type="Component_t" />

  <xs:complexType name="Canvas_t">
    <xs:complexContent>
      <xs:extension base="TopContent_t">
        <xs:attribute ref="Name" use="required"/>
        <xs:attribute ref="Height" use="required"/>
        <xs:attribute ref="Width" use="required"/>
        <xs:attribute ref="Fill" use="required"/>
        <xs:attribute name="Folder" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="Canvas" type="Canvas_t" />

  <xs:complexType name="Content_t">
    <xs:complexContent>
      <xs:extension base="TopContent_t">
        <xs:attributeGroup ref="Element" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Rectangle_t">
    <xs:complexContent>
      <xs:extension base="Content_t">
        <xs:attribute ref="Height" use="required" />
        <xs:attribute ref="Width" use="required" />
        <xs:attribute name="RadiusX" type="xs:string" />
        <xs:attribute name="RadiusY" type="xs:string" />
        <xs:attribute ref="StrokeThickness" />
        <xs:attribute ref="Stroke" />
        <xs:attribute ref="Fill" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="Rectangle" type="Rectangle_t" />

  <xs:complexType name="Ellipse_t">
    <xs:complexContent>
      <xs:extension base="Content_t">
        <xs:attribute ref="Height" use="required" />
        <xs:attribute ref="Width" use="required" />
        <xs:attribute ref="StrokeThickness" />
        <xs:attribute ref="Stroke" />
        <xs:attribute ref="Fill" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="Ellipse" type="Ellipse_t" />

  <xs:complexType name="Line_t">
    <xs:complexContent>
      <xs:extension base="Content_t">
        <xs:attribute name="X1" type="xs:string" use="required" />
        <xs:attribute name="Y1" type="xs:string" use="required" />
        <xs:attribute name="X2" type="xs:string" use="required" />
        <xs:attribute name="Y2" type="xs:string" use="required" />
        <xs:attribute ref="Height" />
        <xs:attribute ref="Width" />
        <xs:attribute ref="StrokeThickness" />
        <xs:attribute ref="Stroke" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="Line" type="Line_t" />

  <xs:element name="TextBlock">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attributeGroup ref="Element" />
          <xs:attribute name="Text" type="xs:string" />
          <xs:attribute name="FontFamily" type="xs:string" />
          <xs:attribute name="FontWeight" type="xs:string" />
          <xs:attribute name="FontStyle" type="xs:string" />
          <xs:attribute name="FontStretch" type="xs:string" />
          <xs:attribute name="FontSize" type="xs:string" />
          <xs:attribute name="Background" type="xs:string" />
          <xs:attribute name="Foreground" type="xs:string" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Image">
    <xs:complexType>
      <xs:attributeGroup ref="Element" />
      <xs:attribute name="Source" type="xs:string" use="required" />
      <xs:attribute ref="Height" />
      <xs:attribute ref="Width" />
    </xs:complexType>
  </xs:element>

  <xs:element name="Set">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute ref="Name"/>
          <xs:attribute ref="Value" />
          <xs:attribute ref="RefName" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="Grid">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Default" minOccurs="0" />
        <xs:element ref="Row" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attributeGroup ref="Element" />
      <xs:attribute ref="RowHeight" use="required" />
      <xs:attribute ref="ColumnWidth" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="Row">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Column" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attributeGroup ref="Element" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Column" type="Content_t" />
  
  <xs:element name="Default" type="Content_t" />
  
  <xs:element name="HotSpot">
    <xs:complexType>
      <xs:attributeGroup ref="Element" />
      <xs:attribute ref="Height" use="required" />
      <xs:attribute ref="Width" use="required" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Ref">
    <xs:complexType>
      <xs:attributeGroup ref="Element" />
      <xs:attribute ref="RefName" />
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== TimPaterson/ScreenDesigner-for-touchscreens/Examples/Keypad/Keypad.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://www.timpaterson.com/schemas/ScreenDesigner.xsd">
  <Set>
    ScreenHeight = 320;
    ScreenWidth = 200;
  	BtnHeight = 60;
  	BtnWidth = 60;
  	KeySpace = 10;
  	BtnFontSize = BtnHeight * 3 / 4;
    KeypadHeight = BtnHeight * 4 + KeySpace * 3;
    KeypadTop = ScreenHeight - KeypadHeight;
    DisplayMargin = 5;
    DisplayWidth = ScreenWidth - DisplayMargin * 2;
    DisplayHeight = KeypadTop - DisplayMargin * 2;
  </Set>
  
  <Font Name="BtnFont" FontSize="BtnFontSize" FontFamily="Arial"/>
  <Color Name="DisplayBackcolor" Color="Yellow"/>
  
  <!-- Components -->
  <Component Name="Display">
    <Rectangle Area="Display" Height="DisplayHeight" Width="DisplayWidth" Left="DisplayMargin" Fill="DisplayBackcolor"/>
  </Component>
  
  <Component Name="Keypad">
    <Grid Top="0" Left="0" RowHeight="BtnHeight + KeySpace" ColumnWidth="BtnWidth + KeySpace">
      <Default>
        <Rectangle Name="Button" Height="BtnHeight" Width="BtnWidth" RadiusX="8" RadiusY="8" Fill="White">
          <TextBlock Name="Label" Font="BtnFont" Foreground="Black"/>
        </Rectangle>
        <Set>
          Button.Group = Digit;
        </Set>
      </Default>
      <Row>
        <Column>
          <Set>
            Label.Text = 7;
            Button.HotSpot = Key_7;
          </Set>
        </Column>
        <Column>
          <Set>
            Label.Text = 8;
            Button.HotSpot = Key_8;
          </Set>
        </Column>
        <Column>
          <Set>
            Label.Text = 9;
            Button.HotSpot = Key_9;
          </Set>
        </Column>
      </Row>
      <Row>
        <Column>
          <Set>
            Label.Text = 4;
            Button.HotSpot = Key_4;
          </Set>
        </Column>
        <Column>
          <Set>
            Label.Text = 5;
            Button.HotSpot = Key_5;
          </Set>
        </Column>
        <Column>
          <Set>
            Label.Text = 6;
            Button.HotSpot = Key_6;
          </Set>
        </Column>
      </Row>
      <Row>
        <Column>
          <Set>
            Label.Text = 1;
            Button.HotSpot = Key_1;
          </Set>
        </Column>
        <Column>
          <Set>
            Label.Text = 2;
            Button.HotSpot = Key_2;
          </Set>
        </Column>
        <Column>
          <Set>
            Label.Text = 3;
            Button.HotSpot = Key_3;
          </Set>
        </Column>
      </Row>
      <Row>
        <Column>
          <Set>
            Label.Text = ±;
            Button.HotSpot = Key_sign;
          </Set>
        </Column>
        <Column>
          <Set>
            Label.Text = 0;
            Button.HotSpot = Key_0;
          </Set>
        </Column>
        <Column>
          <Set>
            Label.Text = ∙;
            Button.HotSpot = Key_decimal;
          </Set>
        </Column>
      </Row>
    </Grid>
  </Component>
  
  <Canvas Name="KeypadUp" Height="ScreenHeight" Width="ScreenWidth" ColorDepth="Color16bpp" Fill="Blue">
    <Ref RefName="Keypad" Top="0"/>
    <Ref RefName="Display" Top="KeypadHeight + DisplayMargin"/>
  </Canvas>
  
  <Canvas Name="KeypadDown" Height="ScreenHeight" Width="ScreenWidth" ColorDepth="Color16bpp" Fill="LightGreen">
    <Ref RefName="Display" Top="DisplayMargin"/>
    <Ref RefName="Keypad" Top="KeypadTop">
      <Set>Button.Fill = Black; Label.Foreground = White</Set>
    </Ref>
  </Canvas>
  
</Project>
